// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyiweleeflytxphcydvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5aXdlbGVlZmx5dHhwaGN5ZHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjA2NDUsImV4cCI6MjA2OTc5NjY0NX0.k6A_NrGRNSJl4dwXTk8tbFONNWW1HlHs415hHpzMTfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});